{% set version = "0.7.10" %}

package:
  name: cython-blis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blis/blis-{{ version }}.tar.gz
  sha256: 343e8b125784d70ff6e1f17a95ea71538705bf0bd3cc236a176d153590842647

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3.0                            # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - clangdev  # [win]
  host:
    - python
    - pip
    - cython <3.0
    - setuptools
    - numpy
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - hypothesis
  imports:
    - blis
    - blis.py
    - blis.cy
  commands:
    - python -m pytest --tb=native --pyargs blis

about:
  home: http://github.com/explosion/cython-blis
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - blis/LICENSE
  summary: Fast matrix-multiplication as a self-contained Python library – no system dependencies!

  doc_url: https://github.com/explosion/cython-blis
  dev_url: https://github.com/explosion/cython-blis

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
