{% set version = "0.7.1" %}

package:
  name: cython-blis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blis/blis-{{ version }}.tar.gz
  sha256: 014771a0f753a64ef5610c5b3d4a090b263073bdd59b8ad0d872ce1e06e7315a

build:
  number: 0
  skip: true  # [win and py27]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev  # [win]
  host:
    - python
    - pip
    - python
    - setuptools
    - numpy 1.16.*
    - wheel
  run:
    - python
    - numpy >=1.16

test:
  imports:
    - blis
    - blis.py
    - blis.cy

about:
  home: http://github.com/explosion/cython-blis
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - blis/LICENSE
  summary: Fast matrix-multiplication as a self-contained Python library – no system dependencies!

  doc_url: https://github.com/explosion/cython-blis
  dev_url: https://github.com/explosion/cython-blis

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
