{% set version = "1.3.0" %}

package:
  name: cython-blis
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/blis/blis-{{ version }}.tar.gz
  sha256: 1695a87e3fc4c20d9b9140f5238cac0514c411b750e8cdcec5d8320c71f62e99

build:
  number: 0
  # if you care about ppc, please debug the failures
  skip: true  # [ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - clangdev  # [win]
  host:
    - python
    - pip
    - cython
    - setuptools
    - numpy
    - wheel
  run:
    - python

test:
  requires:
    - pytest
    - hypothesis
  imports:
    - blis
    - blis.py
    - blis.cy
  commands:
    {% set tests_to_skip = "_not_a_real_test" %}
    # flakiness and likely emulation issues on PPC
    {% set tests_to_skip = tests_to_skip + " or test_memoryview_float_notrans " %}  # [ppc64le]
    - pytest --tb=native --pyargs blis -k "not ({{ tests_to_skip }})"

about:
  home: http://github.com/explosion/cython-blis
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - blis/LICENSE
  summary: Fast matrix-multiplication as a self-contained Python library – no system dependencies!

  doc_url: https://github.com/explosion/cython-blis
  dev_url: https://github.com/explosion/cython-blis

extra:
  recipe-maintainers:
    - conda-forge/spacy
